---
- name: Copy configuration file
  template:
    src: wpa_supplicant-interface.conf
    dest: /etc/wpa_supplicant/wpa_supplicant-{{ wifiname }}
    owner: root
    group: root
    mode: 0644
  become: true
