---
- name: Copy configuration file
  template:
    src: wpa_supplicant-interface.conf
    dest: /etc/wpa_supplicant/wpa_supplicant-{{ iface_name }}.conf
    owner: root
    group: root
    mode: 0644
  become: true

- name: Copy systemd-networkd config
  template:
    src: interface.network.j2
    dest: /etc/systemd/network/{{ iface_name }}.network
    owner: root
    group: root
    mode: 0644
  become: true
