---
- name: Start the service
  systemd:
    name: wpa_supplicant@{{ iface_name }}
    state: started
    enabled: yes
  become: true

- name: Start systemd-networkd service
  systemd:
    name: systemd-networkd
    state: restarted
    enabled: yes
  become: true
