---
#
# Play: Bootstrap pacman and python so we can run Ansible.
#
- hosts: all
  gather_facts: no
  tasks:
    - name: Bootstrap the system
      raw: pacman-key --init && pacman-key --populate archlinuxarm && pacman -Sy && pacman --noconfirm --needed -S python
      become: true

#
# Play: Create system users and generate SSH keys.
#
- hosts: all
  gather_facts: no
  vars_files:
    - vars/main.yaml
    - vars/users.yaml
  become: true
  tasks:
    - include_role:
        name: user
      vars:
        username: "{{ item.key }}"
        user: "{{ item.value }}"
      with_dict: "{{ users }}"
      when: item.key != "root" and item.value.system_user | default(true)

#
# Play: Configure other parts of the system, install software.
#
- hosts: all
  vars_files:
    - vars/main.yaml
    - vars/users.yaml
  become: true
  tasks:
    - name: Install dependencies
      pacman:
        name: [ inetutils, parted ]
        state: present
        update_cache: yes

    - name: Resize root partition
      shell: parted ---pretend-input-tty {{ item.device | regex_replace("\d$", "") }} resizepart 2 Yes 100% && resize2fs {{ item.device }}
      with_items: "{{ ansible_mounts }}"
      when: item.mount == "/"

    - import_role:
        name: pip

    - name: Install Python dependencies
      pip:
        name: [ docker ]

    - import_role:
        name: tor

    - import_role:
        name: dosh

    - import_role:
        name: opensshd

    - import_role:
        name: docker

    - name: Pull Docker images
      docker_image:
        name: "{{ item.value.image }}"
      with_dict: "{{ users }}"
      when: item.value.image is defined and item.value.image != ""

    - name: Disable default user account {{ default_user }}
      user:
        name: "{{ default_user }}"
        password_lock: yes
        shell: /bin/nologin

    - name: Change hostname
      hostname:
        name: "{{ hostname }}"

#
# Play: Fetch various resources from remote hosts and store them locally.
#
- hosts: all
  vars_files:
    - vars/main.yaml
    - vars/users.yaml
  become: true
  tasks:
    - name: Fetch SSH private keys
      fetch:
        src: "{{ (user.home | default('/home/' + username)) + '/.ssh/id_rsa' }}"
        dest: "{{ resource_store }}"
        fail_on_missing: no
      with_dict: "{{ users }}"
      when: item.value.system_user | default(true)

