---
- hosts: all
  gather_facts: no
  tasks:
    - name: Bootstrap the system
      raw: pacman-key --init && pacman-key --populate archlinuxarm && pacman -Sy && pacman --noconfirm --needed -S python
      become: true

- hosts: all
  vars_files:
    - vars/main.yaml
    - vars/users.yaml
  become: true
  tasks:
    - name: Install dependencies
      pacman:
        name: [ inetutils, parted ]
        state: present
        update_cache: yes

    - name: Resize root partition {{ rootfs_dev }}
      shell: parted ---pretend-input-tty {{ storage_dev }} resizepart 2 Yes 100% && resize2fs {{ rootfs_dev }}

    - name: Change hostname
      hostname:
        name: "{{ hostname }}"

    - import_role:
        name: opensshd

    - import_role:
        name: docker

    - import_role:
        name: tor

    - import_role:
        name: dosh

    - name: Create system users
      user:
        name: "{{ item.key }}"
        generate_ssh_key: yes
        password: "{{ item.value.password | password_hash('sha512', password_salt) }}"
        update_password: always
        groups: [ docker ]
        shell: "{{ item.value.shell | default('/bin/bash') }}"
        state: present
      with_dict: "{{ users }}"
      when: item.value.system_user | default(true)

    - name: Authorize SSH keys
      authorized_key:
        user: "{{ item.key }}"
        key: "{{ lookup('file', '/home/' + item.key + '/.ssh/id_rsa.pub') }}"
        state: present
      with_dict: "{{ users }}"
      when: item.value.system_user | default(true)

    - name: Generate root's SSH key
      user:
        name: root
        generate_ssh_key: yes

    - name: Authorize root SSH key
      authorized_key:
        user: root
        key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
        state: present

    - name: Pull Docker images
      docker_image:
        name: "{{ item.value.image }}"
      with_dict: "{{ users }}"
      when: item.value.image is defined and item.value.image != ""

    #- name: Change root's password
    #  user:
    #    name: root
    #    password: "{{ root_password | password_hash('sha512', password_salt) }}"

    #- name: Disable default user account {{ default_user }}
    #  user:
    #    name: "{{ default_user }}"
    #    password_lock: yes
    #    shell: /bin/nologin

