---
- hosts: all
  vars_files:
    - vars/main.yaml
  tasks:
    - name: Initialize pacman keyring
      shell: pacman-key --init
      become: true

    - name: Import package signing keys
      shell: pacman-key --populate archlinuxarm
      become: true

    - name: Create user "{{ user }}"
      user:
        name: "{{ user }}"
        generate_ssh_key: yes
        password: "{{ user_password | password_hash('sha512', password_salt) }}"
        update_password: always
        shell: /bin/false
        state: present
      become: true
      #register: user_data

    - name: Change hostname
      hostname:
        name: "{{ hostname }}"

    - import_role:
        name: docker

