---
- hosts: all
  gather_facts: no
  tasks:
    - name: Bootstrap node
      raw: su -l root -c "pacman-key --init && pacman-key --populate archlinuxarm && pacman -Sy && pacman -S python"

- hosts: all
  vars_files:
    - vars/main.yaml
  tasks:
    - name: Install dependencies
      pacman:
        name: [ inetutils, parted ]
        state: present
        update_cache: yes

    - name: Resize root partition
      # TODO: determine correct device - either /dev/sda | /dev/mmcblkp1
      # TODO: determine correct partition number!
      shell: parted /dev/sda resizepart 2 Yes 100% print && resize2fs /dev/sda2
      become: true

    - name: Create user "{{ user }}"
      user:
        name: "{{ user }}"
        generate_ssh_key: yes
        password: "{{ user_password | password_hash('sha512', password_salt) }}"
        update_password: always
        shell: /bin/false
        state: present
      become: true
      #register: user_data

    - name: Change hostname
      hostname:
        name: "{{ hostname }}"

    - import_role:
        name: docker

