---
- hosts: all
  gather_facts: no
  tasks:
    - name: Bootstrap the system
      raw: pacman-key --init && pacman-key --populate archlinuxarm && pacman -Sy && pacman --noconfirm --needed -S python
      become: true

- hosts: all
  vars_files:
    - vars/main.yaml
  tasks:
    - name: Install dependencies
      pacman:
        name: [ inetutils, parted ]
        state: present
        update_cache: yes

    - name: Resize root partition {{ rootfs_dev }}
      shell: parted ---pretend-input-tty {{ storage_dev }} resizepart 2 Yes 100% && resize2fs {{ rootfs_dev }}
      become: true

    - name: Change hostname
      hostname:
        name: "{{ hostname }}"

    - import_role:
        name: opensshd

    - import_role:
        name: docker

    - name: Create user "{{ user }}"
      user:
        name: "{{ user }}"
        generate_ssh_key: yes
        password: "{{ user_password | password_hash('sha512', password_salt) }}"
        update_password: always
        groups: [ docker ]
        shell: /bin/bash
        state: present
      become: true

    #- name: Disable default user account {{ default_user }}
    #  user:
    #    name: "{{ default_user }}"
    #    password_lock: yes
    #    shell: /bin/nologin

